72 implanting rollbar on the frontend
bridgefinancial/bridge-nextjs pull request #73
Opened 2024-11-09 23:13 UTC by landonwjohnson

The **rollbar.service** is initialized within the services layer. I've also updated the **error boundary** to use Rollbar’s built-in error boundary. I recommend adding Rollbar logging to the **catch** blocks within the service methods.

There’s also a **useRollbar** method available from the package, which you can utilize as needed. Alternatively, if you'd prefer to display error messages through toast notifications, you can use the **useErrors** hook already set up. I held off on implementing this to avoid making too many changes at once.

2024-11-09 23:17 UTC, whitagar commented on src/services/rollbar.service.ts
> +  accessToken: '26a9695b30054699ae5a8df321ffba09',
We should probably use environment variables for this

2024-11-10 05:39 UTC, whitagar requested changes

2024-11-10 05:39 UTC, whitagar commented on environments/environment.ts
> +    process.env['ROLLBAR_ACCESS_TOKEN'] ?? '26a9695b30054699ae5a8df321ffba09',
this will need to be `NEXT_PUBLIC_ROLLBAR_ACCESS_TOKEN` in order to access it client-side

2024-11-11 19:19 UTC, landonwjohnson commented on environments/environment.ts
> +    process.env['ROLLBAR_ACCESS_TOKEN'] ?? '26a9695b30054699ae5a8df321ffba09',
that's been resolved

2024-11-12 00:34 UTC, whitagar approved these changes

2024-11-13 19:13 UTC, merged